---
- name: Ensure OS is Ubuntu
  assert:
    that: "ansible_distribution == 'Ubuntu'"
    msg: "This role currently supports Ubuntu based systems."

# Variable setup.
- name: Include OS-specific variables
  include_vars: "{{ item }}"
  with_first_found:
    - "{{ ansible_distribution }}-{{ ansible_distribution_major_version }}.yml"
    - "{{ ansible_distribution }}.yml"

- name: Set PHP version
  set_fact:
    php_version: "{{ __php_version }}"
  when: php_version is not defined

- name: Set base php_packages
  set_fact:
    php_packages: "{{ __php_packages | list }}"
  when: php_packages is not defined

- name: Update php_packages with any php_packages_extra
  set_fact:
    php_packages: "{{ php_packages | list + php_packages_extra | list }}"
  when: php_packages_extra is defined

- name: Set php_server_apis
  set_fact:
    php_server_apis: "{{ __php_server_apis }}"
  when: php_server_apis is not defined

- name: Set php_conf_path
  set_fact:
    php_conf_path: "{{ __php_conf_path }}"
  when: php_conf_path is not defined

# Setup
- import_tasks: setup-Debian.yml
  when: ansible_os_family == 'Debian'

# Configure
- import_tasks: configure.yml
- import_tasks: configure-fpm.yml
- import_tasks: configure-opcache.yml
