---
- name: Update apt cache
  apt:
    update_cache: true
    cache_valid_time: 3600

- name: Install PHP packages
  apt:
    name: "{{ item }}"
    state: present
  with_items: "{{ php_packages }}"
